[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/assets/img/generated",
    ".cache"
  ]

[build.environment]
  NODE_VERSION = "lts/*"

[[redirects]]
  from = "https://11tybundle.dev/categories/frontmatter/"
  to = "https://11tybundle.dev/categories/front-matter/"
  status = 301
