[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache"
  ]

[[redirects]]
  from = "https://www.11tybundle.dev/categories/frontmatter/"
  to = "https://www.11tybundle.dev/categories/front-matter/"
  status = 301
